/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.awt.Color;
import br.ulbra.dao.ConnectionFactory;
import br.ulbra.dao.usuarioDao;
import java.sql.SQLException;

/**
 *
 * @author troll
 */
public class frLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form frLogin
     */
    public frLogin(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSenhaDica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btLogar = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Login");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSenhaDica.setEditable(false);
        txtSenhaDica.setForeground(new java.awt.Color(102, 102, 102));
        txtSenhaDica.setText("Insira aqui sua senha");
        txtSenhaDica.setToolTipText("");
        txtSenhaDica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSenhaDicaMousePressed(evt);
            }
        });
        txtSenhaDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaDicaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenhaDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 100, 230, 25));

        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 31, -1, -1));

        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 82, -1, -1));

        txtSenha.setMaximumSize(new java.awt.Dimension(108, 20));
        txtSenha.setMinimumSize(new java.awt.Dimension(108, 20));
        txtSenha.setPreferredSize(new java.awt.Dimension(108, 20));
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 100, 230, 25));

        btLogar.setText("Logar");
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });
        jPanel1.add(btLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 133, -1, -1));

        txtLogin.setEditable(false);
        txtLogin.setForeground(new java.awt.Color(102, 102, 102));
        txtLogin.setText("Insira aqui seu email");
        txtLogin.setToolTipText("");
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLoginMousePressed(evt);
            }
        });
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 51, 230, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Boolean a = false;
    private void txtSenhaDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaDicaActionPerformed
        txtSenhaDica.setText(null);
        txtSenhaDica.setForeground(Color.black);
    }//GEN-LAST:event_txtSenhaDicaActionPerformed

    private void txtSenhaDicaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSenhaDicaMousePressed
        txtSenhaDica.hide();
        txtSenha.grabFocus();
    }//GEN-LAST:event_txtSenhaDicaMousePressed

    private void txtLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMousePressed
        
        if(a == false) {
        txtLogin.setText(null);
        txtLogin.setForeground(Color.black);
        txtLogin.setEditable(true);
        a = true;
        }else {
            
        }
    }//GEN-LAST:event_txtLoginMousePressed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        usuarioDao usu = null;
        String email = txtLogin.getText();
        String senha = txtSenha.getText();
        
        
    }//GEN-LAST:event_btLogarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSenhaDica;
    // End of variables declaration//GEN-END:variables
}
