/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.ConnectionFactory;
import br.ulbra.dao.UsuarioDao;
import java.sql.SQLException;
/**
 *
 * @author troll
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu(){
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem2 = new javax.swing.JMenuItem();
        saveMenuItem3 = new javax.swing.JMenuItem();
        saveMenuItem4 = new javax.swing.JMenuItem();
        saveMenuItem5 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        saveMenuItem6 = new javax.swing.JMenuItem();
        saveMenuItem7 = new javax.swing.JMenuItem();
        saveMenuItem8 = new javax.swing.JMenuItem();
        saveMenuItem9 = new javax.swing.JMenuItem();
        saveMenuItem10 = new javax.swing.JMenuItem();
        saveMenuItem11 = new javax.swing.JMenuItem();
        saveMenuItem12 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Cadastro de usuário");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveMenuItem1.setMnemonic('s');
        saveMenuItem1.setText("Cadastro de sala");
        saveMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem1);

        saveMenuItem2.setMnemonic('s');
        saveMenuItem2.setText("Cadastro de controle");
        saveMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem2);

        saveMenuItem3.setMnemonic('s');
        saveMenuItem3.setText("Cadastro de marca");
        saveMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem3ActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem3);

        saveMenuItem4.setMnemonic('s');
        saveMenuItem4.setText("Cadastro de hardware");
        saveMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem4);

        saveMenuItem5.setMnemonic('s');
        saveMenuItem5.setText("Cadastro de categoria");
        saveMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem5ActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem5);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Consultas");

        saveMenuItem6.setMnemonic('s');
        saveMenuItem6.setText("Consulta de usuário");
        saveMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem6ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem6);

        saveMenuItem7.setMnemonic('s');
        saveMenuItem7.setText("Consulta de sala");
        saveMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem7ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem7);

        saveMenuItem8.setMnemonic('s');
        saveMenuItem8.setText("Consulta de controle");
        saveMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem8ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem8);

        saveMenuItem9.setMnemonic('s');
        saveMenuItem9.setText("Consulta  de marca");
        saveMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem9ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem9);

        saveMenuItem10.setMnemonic('s');
        saveMenuItem10.setText("Consulta  de hardware");
        saveMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem10ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem10);

        saveMenuItem11.setMnemonic('s');
        saveMenuItem11.setText("Consulta  de categoria");
        saveMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem11ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem11);

        saveMenuItem12.setMnemonic('s');
        saveMenuItem12.setText("Consulta de controle de hardware");
        saveMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem12ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem12);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("perfil");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sair");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        FrCadUsu cadUsu = new FrCadUsu();
        desktopPane.add(cadUsu);
        cadUsu.setVisible(true);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem1ActionPerformed
        FrCadSala cadSala = new FrCadSala();
        desktopPane.add(cadSala);
        cadSala.setVisible(true);
    }//GEN-LAST:event_saveMenuItem1ActionPerformed
        
    private void saveMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItem2ActionPerformed

    private void saveMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem3ActionPerformed
        FrCadMarca cadMarca = new FrCadMarca();
        desktopPane.add(cadMarca);
        cadMarca.setVisible(true);
    }//GEN-LAST:event_saveMenuItem3ActionPerformed

    private void saveMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem4ActionPerformed
        FrCadHard cadMarca = new FrCadHard();
        desktopPane.add(cadMarca);
        cadMarca.setVisible(true);
    }//GEN-LAST:event_saveMenuItem4ActionPerformed

    private void saveMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem5ActionPerformed
        FrCadCategoria CadCategoria = new FrCadCategoria();
        desktopPane.add(CadCategoria);
        CadCategoria.setVisible(true);
    }//GEN-LAST:event_saveMenuItem5ActionPerformed

    private void saveMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem6ActionPerformed
        FrConUsu conUsu = new FrConUsu();
        desktopPane.add(conUsu);
        conUsu.setVisible(true);
    }//GEN-LAST:event_saveMenuItem6ActionPerformed

    private void saveMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem7ActionPerformed
        FrConSala conSala = new FrConSala();
        desktopPane.add(conSala);
        conSala.setVisible(true);
    }//GEN-LAST:event_saveMenuItem7ActionPerformed

    private void saveMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItem8ActionPerformed

    private void saveMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem9ActionPerformed
        FrConMarca conMarca = new FrConMarca();
        desktopPane.add(conMarca);
        conMarca.setVisible(true);
    }//GEN-LAST:event_saveMenuItem9ActionPerformed

    private void saveMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem10ActionPerformed
        FrConHard conHard = new FrConHard();
        desktopPane.add(conHard);
        conHard.setVisible(true);
    }//GEN-LAST:event_saveMenuItem10ActionPerformed

    private void saveMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem11ActionPerformed
        FrConCategoria conMarca = new FrConCategoria();
        desktopPane.add(conMarca);
        conMarca.setVisible(true);
    }//GEN-LAST:event_saveMenuItem11ActionPerformed

    private void saveMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMenuItem12ActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        this.dispose();
        new FrLogin().setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveMenuItem1;
    private javax.swing.JMenuItem saveMenuItem10;
    private javax.swing.JMenuItem saveMenuItem11;
    private javax.swing.JMenuItem saveMenuItem12;
    private javax.swing.JMenuItem saveMenuItem2;
    private javax.swing.JMenuItem saveMenuItem3;
    private javax.swing.JMenuItem saveMenuItem4;
    private javax.swing.JMenuItem saveMenuItem5;
    private javax.swing.JMenuItem saveMenuItem6;
    private javax.swing.JMenuItem saveMenuItem7;
    private javax.swing.JMenuItem saveMenuItem8;
    private javax.swing.JMenuItem saveMenuItem9;
    // End of variables declaration//GEN-END:variables

}
